### PR TITLE
be more lenient about rootdir

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by Keno** [comment]
What is the motivation for this change?

**Comment by vchuravy** [comment]
I am working on a cluster environment where the installation pattern is `ROOT_DIR/include` instead of `ROOT_DIR/usr/include`

**Comment by Keno** [comment]
I think I'd be fine with just making it  `CXXJL_ROOTDIR = get(ENV, "CXXJL_ROOTDIR", "/usr")`

**Comment by vchuravy** [comment]
done.

**Pull request merged**
