### PR TITLE
Fix building with an out-of-tree Julia.

### PR DESCRIPTION
**Pull request by maleadt**
This splits `BASE_JULIA_HOME` into `BASE_JULIA_BIN` and `BASE_JULIA_SRC` (with the added change that `BASE_JULIA_BIN` now points to the root, and not the `usr/bin` subfolder). This allows building in the case of an out-of-tree Julia build, requiring the user to override `BASE_JULIA_SRC` when building deps.

Tested on 0.5, fresh checkout with the `Make.user` options from the README, as well as with my out-of-tree set-up.

### CODE REVIEW

**Comment by Keno** [comment]
Seems to have failed CI?

**Comment by maleadt** [comment]
Yeah, I messed up with defining `$JULIA_BIN` as `$JULIA_HOME/../..` and using `JULIA_BIN/usr/$whatever`, which doesn't work with eg. dists where there's no `usr` folder. Will be updating soon.

**Comment by maleadt** [comment]
Fixed the OOB build (passing CI now).

Also sneaked in a seemingly benign fix to the `Makefile` to actually get it to build clang when using a binary dist, but that seems to make Travis go crazy?

**Comment by Keno** [comment]
OS X Travis is broken for unknown reasons.

**Comment by oschulz** [comment]
> Also sneaked in a seemingly benign fix to the Makefile to actually get it to build clang when using a binary dist

Thanks, this is awesome - using Cxx without a specially-build Julia will make things a lot easier and lower the barrier for many users. I just tried it, works like a charm. One question: The resulting Cxx package dir is huge (1.2 GB on my machine), because of the full clang/llvm src and build in there. Would it be possible to run some kind of "make install" (e.g. to Cxx/deps/usr), and then delete deps/src and deps/build? I have a feeling that this could result in substantial space savings.

**Pull request merged**
